export const FETCH_ARTICLES_GLOBALLY_REQUEST = 'FETCH_ARTICLES_GLOBALLY_REQUEST';
export const FETCH_ARTICLES_GLOBALLY_SUCCESS = 'FETCH_ARTICLES_GLOBALLY_SUCCESS';
export const FETCH_ARTICLES_GLOBALLY_ERROR = 'FETCH_ARTICLES_GLOBALLY_ERROR';

export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_IS_AUTHORISED = 'SET_IS_AUTHORISED';

export const FETCH_REGISTER_REQUEST = 'FETCH_REGISTER_REQUEST';
export const FETCH_REGISTER_SUCCESS = 'FETCH_REGISTER_SUCCESS';
export const FETCH_REGISTER_ERROR = 'FETCH_REGISTER_ERROR';
