export const FETCH_ARTICLES_GLOBALLY_REQUEST = 'FETCH_ARTICLES_GLOBALLY_REQUEST';
export const FETCH_ARTICLES_GLOBALLY_SUCCESS = 'FETCH_ARTICLES_GLOBALLY_SUCCESS';
export const FETCH_ARTICLES_GLOBALLY_ERROR = 'FETCH_ARTICLES_GLOBALLY_ERROR';
