export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_IS_AUTHORISED = 'SET_IS_AUTHORISED';
export const SET_USER_NAME = 'SET_USER_NAME';
export const SET_USER_IMAGE = 'SET_USER_IMAGE';
export const SET_IS_USER_AUTHOR = 'SET_IS_USER_AUTHOR';
export const SET_CREATED_STATUS = 'SET_CREATED_STATUS';

export const FETCH_ARTICLES_GLOBALLY_REQUEST = 'FETCH_ARTICLES_GLOBALLY_REQUEST';
export const FETCH_ARTICLES_GLOBALLY_SUCCESS = 'FETCH_ARTICLES_GLOBALLY_SUCCESS';
export const FETCH_ARTICLES_GLOBALLY_ERROR = 'FETCH_ARTICLES_GLOBALLY_ERROR';

export const FETCH_REGISTER_REQUEST = 'FETCH_REGISTER_REQUEST';
export const FETCH_REGISTER_SUCCESS = 'FETCH_REGISTER_SUCCESS';
export const FETCH_REGISTER_ERROR = 'FETCH_REGISTER_ERROR';

export const FETCH_LOGIN_REQUEST = 'FETCH_LOGIN_REQUEST';
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';
export const FETCH_LOGIN_ERROR = 'FETCH_LOGIN_ERROR';

export const FETCH_UPDATE_REQUEST = 'FETCH_UPDATE_REQUEST';
export const FETCH_UPDATE_SUCCESS = 'FETCH_UPDATE_SUCCESS';
export const FETCH_UPDATE_ERROR = 'FETCH_UPDATE_ERROR';

export const FETCH_CREATE_ARTICLE_REQUEST = 'FETCH_CREATE_ARTICLE_REQUEST';
export const FETCH_CREATE_ARTICLE_SUCCESS = 'FETCH_CREATE_ARTICLE_SUCCESS';
export const FETCH_CREATE_ARTICLE_ERROR = 'FETCH_CREATE_ARTICLE_ERROR';

export const FETCH_DELETE_ARTICLE_REQUEST = 'FETCH_DELETE_ARTICLE_REQUEST';
export const FETCH_DELETE_ARTICLE_SUCCESS = 'FETCH_DELETE_ARTICLE_SUCCESS';
export const FETCH_DELETE_ARTICLE_ERROR = 'FETCH_DELETE_ARTICLE_SUCCESS';

export const FETCH_EDIT_ARTICLE_REQUEST = 'FETCH_EDIT_ARTICLE_REQUEST';
export const FETCH_EDIT_ARTICLE_SUCCESS = 'FETCH_EDIT_ARTICLE_SUCCESS';
export const FETCH_EDIT_ARTICLE_ERROR = 'FETCH_EDIT_ARTICLE_ERROR';
